### ISSUE TITLE
I found the same problem, but I solved it

### ISSUE THREAD

**Issue by guzishiwo** [mike-engel/split-view-test#1]
Need to drag View
```swift
HSplitView {
    View1()
    View2()
}
```
Intuitively, we will set the maximum width of View1, **but when SwiftUI drags, View1 exceeds the maximum width, it will display an inexplicable error**
```swift
HSplitView {
    View1()
        .frame(maxWidth: 300)
    View2()
}
```
**Solutions**
**Set the minimum width of View2**, and let View automatically fill all spaces. There will be no drag problem

```swift
HSplitView {
    View1()
    View2()
        .frame(minWidth: 500)
}
```

**Comment by mike-engel** [comment]
Thanks @guzishiwo! This won't work for my case, however. I have two views in a window. The window can be resized. `View1` should only be able to be 300 pixels wide.

In order for your solution to work, I would need to know the size of the window when setting the `minWidth` of `View2`. It's probably possible with `GeometryReader`, but I shouldn't need to do that.

If the window is 1000 pixels wide, `View2` would need `minWidth: 700`. But if the window was resized by the user to be 1500 pixels wide, `View2` would then need to have `minWidth: 1200`.
